// Insurance listings data
export const insuranceListings = [
  {
    title: "SushiSwap",
    provider: "SushiSwap Insurance Token",
    minRate: "3.45",
    maxRate: "3.73",
    capacity: "4.8k",
    capacityUSD: "22.6",
    isNew: true,
    protocol: "exchange" as const,
  },
  {
    title: "Curve Finance",
    provider: "Curve Finance Insurance Token",
    minRate: "2.51",
    maxRate: "2.62",
    capacity: "4.8k",
    capacityUSD: "22.4",
    isNew: false,
    protocol: "defi" as const,
  },
  {
    title: "Aave",
    provider: "Aave Insurance Token",
    minRate: "0.55",
    maxRate: "0.59",
    capacity: "3.7k",
    capacityUSD: "17.3",
    isNew: false,
    protocol: "lending" as const,
  },
  {
    title: "Uniswap V3",
    provider: "Uniswap Insurance Token",
    minRate: "1.25",
    maxRate: "1.45",
    capacity: "8.2k",
    capacityUSD: "38.5",
    isNew: false,
    protocol: "exchange" as const,
  },
  {
    title: "Compound",
    provider: "Compound Insurance Token",
    minRate: "1.80",
    maxRate: "2.10",
    capacity: "6.1k",
    capacityUSD: "28.7",
    isNew: false,
    protocol: "lending" as const,
  },
  {
    title: "MakerDAO",
    provider: "MakerDAO Insurance Token",
    minRate: "0.75",
    maxRate: "0.95",
    capacity: "12.3k",
    capacityUSD: "58.9",
    isNew: false,
    protocol: "defi" as const,
  },
];